# Generated by Django 5.1.5 on 2025-02-03 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria_producto', models.CharField(max_length=100)),
                ('descripcion_categoria_producto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('rol_perfil', models.CharField(max_length=50)),
                ('permisos_perfil', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_pedido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formapago_pedido', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], max_length=10)),
                ('estado_pedido', models.CharField(choices=[('borrador', 'Borrador'), ('pedido', 'Pedido'), ('cancelado', 'Cancelado'), ('facturado', 'Facturado')], default='borrador', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_producto', models.IntegerField()),
                ('descripcion_producto', models.TextField()),
                ('foto_producto', models.ImageField(upload_to='productos/')),
                ('id_categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoriaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Detallepedidos',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido_usuario', models.CharField(max_length=100)),
                ('fecha_nacimiento_usuario', models.DateField(blank=True, null=True)),
                ('genero_usuario', models.CharField(max_length=20, null=True)),
                ('fecharegistro_usuario', models.DateTimeField(null=True)),
                ('activo_usuario', models.BooleanField(default=True, null=True)),
                ('direccion_usuario', models.CharField(max_length=200, null=True)),
                ('telefono_usuario', models.CharField(max_length=10, null=True)),
                ('email_usuario', models.EmailField(max_length=254, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario'),
        ),
    ]
