# Generated by Django 5.1.4 on 2025-01-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='activo_usuario',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion_usuario',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_usuario',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento_usuario',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecharegistro_usuario',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero_usuario',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_usuario',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
