# Generated by Django 5.1.5 on 2025-02-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_pedido_user_pedido_forma_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_pedido',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
