# Generated by Django 5.1.4 on 2025-01-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_usuario_activo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento_usuario',
            field=models.DateField(blank=True, null=True),
        ),
    ]
