# Generated by Django 5.1.4 on 2025-01-30 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_rename_apelllido_usuario_usuario_apellido_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedidos',
            name='id_pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.pedido'),
        ),
    ]
