# Generated by Django 5.1.4 on 2025-01-06 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria_producto', models.CharField(max_length=100)),
                ('descripcion_categoria_producto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('rol_perfil', models.CharField(max_length=50)),
                ('permisos_perfil', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apelllido_usuario', models.CharField(max_length=100)),
                ('fecha_nacimiento_usuario', models.DateField()),
                ('genero_usuario', models.CharField(max_length=20)),
                ('fecharegistro_usuario', models.DateTimeField()),
                ('activo_usuario', models.BooleanField(default=True)),
                ('direccion_usuario', models.CharField(max_length=200)),
                ('telefono_usuario', models.CharField(max_length=10)),
                ('email_usuario', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_producto', models.IntegerField()),
                ('descripcion_producto', models.TextField()),
                ('foto_producto', models.ImageField(upload_to='productos/')),
                ('id_categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoriaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Detallepedidos',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('formapago_pedido', models.CharField(max_length=10)),
                ('estado_pedido', models.CharField(choices=[('borrador', 'Borrador'), ('pedido', 'pedido'), ('cancelado', 'cancelado'), ('facturado', 'facturado')], default='borrador', max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario')),
            ],
        ),
    ]
